#!/usr/bin/env sh
if [ $USER = root ]; then
    SUDO=""
elif [ ! -z $(which sudo) ]; then
    SUDO=sudo
elif [ ! -z $(which doas) ]; then
    SUDO=doas
else
    USE_SU="true"
fi
MSG="Successfully installed createquick"
[ -e /usr/bin/cq ] && MSG="Successfully reinstalled createquick"
THISDIR=$(dirname $0)
chmod +x $THISDIR/cq
COMMAND="cp $THISDIR/cq /usr/bin && echo $MSG"
if [ ! -z $USE_SU ]; then
    su -c "$COMMAND"
else
    sh -c "$SUDO $COMMAND"
fi
